server.port: 8989

#spring.rabbitmq.host: 192.168.99.100
#spring.rabbitmq.port: 5672
#spring.rabbitmq.username: guest
#spring.rabbitmq.password: guest

eureka.client.register-with-eureka: false
eureka.client.fetch-registry: false
logging.level.com.netflix.eureka: OFF
logging.level.com.netflix.discovery: OFF
